// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKgiaOHXe8k0mLhGSpVYF1DsGnVnNfSmQ',
    appId: '1:330163001550:web:4e4e61f3bab540040ed89f',
    messagingSenderId: '330163001550',
    projectId: 'pedrodelivery-d3300',
    authDomain: 'pedrodelivery-d3300.firebaseapp.com',
    storageBucket: 'pedrodelivery-d3300.appspot.com',
    measurementId: 'G-2D6EMW5SFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAarfMey9dQQR3DJkBy_4s0MIgh4CQJO3M',
    appId: '1:330163001550:android:a7758f7341c5997b0ed89f',
    messagingSenderId: '330163001550',
    projectId: 'pedrodelivery-d3300',
    storageBucket: 'pedrodelivery-d3300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPAREL5pBPdPd_8bIyVkSwtn-Oq_Mefrw',
    appId: '1:330163001550:ios:829d005b8426733e0ed89f',
    messagingSenderId: '330163001550',
    projectId: 'pedrodelivery-d3300',
    storageBucket: 'pedrodelivery-d3300.appspot.com',
    iosBundleId: 'com.example.dataPersistence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPAREL5pBPdPd_8bIyVkSwtn-Oq_Mefrw',
    appId: '1:330163001550:ios:829d005b8426733e0ed89f',
    messagingSenderId: '330163001550',
    projectId: 'pedrodelivery-d3300',
    storageBucket: 'pedrodelivery-d3300.appspot.com',
    iosBundleId: 'com.example.dataPersistence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKgiaOHXe8k0mLhGSpVYF1DsGnVnNfSmQ',
    appId: '1:330163001550:web:1b4b1d3fac347db90ed89f',
    messagingSenderId: '330163001550',
    projectId: 'pedrodelivery-d3300',
    authDomain: 'pedrodelivery-d3300.firebaseapp.com',
    storageBucket: 'pedrodelivery-d3300.appspot.com',
    measurementId: 'G-G7NN618CP0',
  );
}
